[package]
name = "aoc_solution"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path = "../aoc_utils" }
bit-vec = "0.6.3"
indoc = "1.0.3"

[env]
RUST_BACKTRACE = "1"
